### ISSUE TITLE
add additional layer to mesh node architecture

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/pcwnetworkmap#2]
we should add an additional layer distinguishing wired and wireless connections. the current map shows connections going from gotham to individual access points. but all connections from gotham should go to the litebeam/router, and then from the router, a series of wired connections to individual aps. those wired connections should look different than the wireless connections between these wired access points and the mesh nodes

**Comment by fmvaldezg** [comment]
https://fmvaldezg.github.io/PCW_animatedlines/

**Comment by fmvaldezg** [comment]
This new version has three levels of connections and added an additional type of points. Colors and symbols to be defined.

**Comment by hawc2** [comment]
looks good to me @fmvaldezg if you want to implement it here

**Comment by hawc2** [comment]
@fmvaldezg do you think this is ready to deploy on the main website?

**Comment by fmvaldezg** [comment]
I implemented the new network map. It is working.
