### ISSUE TITLE
make map key toggleable

### ISSUE THREAD

**Issue by hawc2** [phillycommunitywireless/pcwnetworkmap#4]
make map key toggleable so that the map can be viewed without the key. this is especially important for looking at the map on your phone

**Comment by fmvaldezg** [comment]
Added javascript animation to toggle the map key.

**Comment by fmvaldezg** [comment]
Added javascript code to toggle map key.

<img width="1724" alt="Screenshot 2024-05-28 at 3 44 44 PM" src="https://github.com/phillycommunitywireless/pcwnetworkmap/assets/24557599/24885e6b-0532-4644-b2d1-5346d631a7fd">
